(ns javafx.scene.effect
  (:require [javafx-wrapper :refer :all]))

(defobject blend javafx.scene.effect.Blend)
(defobject bloom javafx.scene.effect.Bloom)
(defobject box-blur javafx.scene.effect.BoxBlur)
(defobject color-adjust javafx.scene.effect.ColorAdjust)
(defobject color-input javafx.scene.effect.ColorInput)
(defobject displacement-map javafx.scene.effect.DisplacementMap)
(defobject drop-shadow javafx.scene.effect.DropShadow)
(defobject gaussian-blur javafx.scene.effect.GaussianBlur)
(defobject glow javafx.scene.effect.Glow)
(defobject image-input javafx.scene.effect.ImageInput)
(defobject inner-shadow javafx.scene.effect.InnerShadow)
(defobject lighting javafx.scene.effect.Lighting)
(defobject motion-blur javafx.scene.effect.MotionBlur)
(defobject perspective-transform javafx.scene.effect.PerspectiveTransform)
(defobject reflection javafx.scene.effect.Reflection)
(defobject sepia-tone javafx.scene.effect.SepiaTone)
(defobject shadow javafx.scene.effect.Shadow)
(defobject float-map javafx.scene.effect.FloatMap)
(defobject light-distant javafx.scene.effect.Light$Distant)
(defobject light-point javafx.scene.effect.Light$Point)
(defobject light-spot javafx.scene.effect.Light$Spot)
