(ns javafx.scene.shape
  (:require [javafx-wrapper :refer :all]))

(defobject triangle-mesh javafx.scene.shape.TriangleMesh)
(defobject arc javafx.scene.shape.Arc)
(defobject circle javafx.scene.shape.Circle)
(defobject cubic-curve javafx.scene.shape.CubicCurve)
(defobject ellipse javafx.scene.shape.Ellipse)
(defobject line javafx.scene.shape.Line)
(defobject path javafx.scene.shape.Path
  ([] (javafx.scene.shape.Path.))
  ([& elements] (javafx.scene.shape.Path. (seq elements))))
(defobject polygon javafx.scene.shape.Polygon)
(defobject polyline javafx.scene.shape.Polyline)
(defobject quad-curve javafx.scene.shape.QuadCurve)
(defobject rectangle javafx.scene.shape.Rectangle)
(defobject svg-path javafx.scene.shape.SVGPath)
(defobject box javafx.scene.shape.Box)
(defobject cylinder javafx.scene.shape.Cylinder)
(defobject mesh-view javafx.scene.shape.MeshView)
(defobject sphere javafx.scene.shape.Sphere)
(defobject arc-to javafx.scene.shape.ArcTo)
(defobject close-path javafx.scene.shape.ClosePath)
(defobject cubic-curve-to javafx.scene.shape.CubicCurveTo)
(defobject h-line-to javafx.scene.shape.HLineTo)
(defobject line-to javafx.scene.shape.LineTo)
(defobject move-to javafx.scene.shape.MoveTo)
(defobject quad-curve-to javafx.scene.shape.QuadCurveTo)
(defobject v-line-to javafx.scene.shape.VLineTo)
